=== mzemanek/Operations-Research/Samples/Simplex-v1.0.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">
   <!--xmlns="http://www.fom.de/schemas/operations-research/simplex/ws-2011"-->
   <!-- Simple types -->
   <xs:simpleType name="rationalType">
      <xs:restriction base="xs:string">
         <xs:pattern value="[+-]?(0|([1-9][0-9]*)|((0|[1-9][0-9]*)/[1-9][0-9]*)|([1-9][0-9]*) ((0|[1-9][0-9]*)/[1-9][0-9]*))" />
      </xs:restriction>
   </xs:simpleType>

   <!-- Complex types -->
   <xs:complexType name="columnType">
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute name="index" type="xs:nonNegativeInteger" />
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   
   <xs:complexType name="columnsType">
      <xs:sequence>
         <xs:element maxOccurs="unbounded" name="Column" type="columnType" />
      </xs:sequence>   
   </xs:complexType>
   
   <xs:complexType name="elementType">
      <xs:simpleContent>
         <xs:extension base="rationalType">
            <xs:attribute name="m" type="xs:nonNegativeInteger" use="required" />
            <xs:attribute name="n" type="xs:nonNegativeInteger" use="required" />
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>

   <xs:complexType name="elementsType">
      <xs:sequence>
         <xs:element name="Element" minOccurs="0" maxOccurs="unbounded" type="elementType" />
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="simplexType">
      <xs:sequence>
         <xs:element name="Tableaux" type="tableauxType">
            <xs:unique name="uniqueTableauIndex">
               <xs:selector xpath="Tableau" />
               <xs:field xpath="@index" />
            </xs:unique>
         </xs:element>
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="solutionType">
      <xs:sequence>
         <xs:element maxOccurs="unbounded" name="Element">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:extension base="rationalType">
                     <xs:attribute name="n" type="xs:nonNegativeInteger" use="required" />
                  </xs:extension>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="solutionsType">
      <xs:sequence>
         <xs:element maxOccurs="unbounded" name="Solution" type="solutionType" />
      </xs:sequence>   
   </xs:complexType>
   
   <xs:complexType name="tableauType">
      <xs:sequence>
         <xs:element minOccurs="0" name="Columns" type="columnsType">
            <xs:unique name="uniqueColumnIndex">
               <xs:selector xpath="Column" />
               <xs:field xpath="@index" />
            </xs:unique>
         </xs:element>
         <xs:element name="Elements" type="elementsType">
            <xs:unique name="uniqueElementAccessor">
               <xs:selector xpath="Element" />
               <xs:field xpath="@m" />
               <xs:field xpath="@n" />
            </xs:unique>
         </xs:element>
         <xs:element minOccurs="0" name="Solution" type="solutionType">
            <xs:unique name="uniqueSolutionElementRowAndColumn">
               <xs:selector xpath="Element" />
               <xs:field xpath="@m" />
               <xs:field xpath="@n" />
            </xs:unique>
         </xs:element>
      </xs:sequence>
      <xs:attribute name="index" type="xs:nonNegativeInteger" use="required" />
      <xs:attribute name="previous" type="xs:nonNegativeInteger" />
   </xs:complexType>

   <xs:complexType name="tableauxType">
      <xs:sequence>
         <xs:element maxOccurs="unbounded" name="Tableau" type="tableauType" />
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="transformationType">
      <xs:sequence>
         
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="transformationsType">
      <xs:sequence>
         <xs:element name="Transformation" maxOccurs="unbounded" />
      </xs:sequence>   
   </xs:complexType>
   
   <!-- Document -->
   <xs:element name="OperationsResearch">
      <xs:complexType>
         <xs:choice>
            <xs:element name="Simplex" type="simplexType">
               <xs:key name="TableauKey">
                  <xs:selector xpath="Tableaux/Tableau" />
                  <xs:field xpath="@index" />
               </xs:key>
            </xs:element>
         </xs:choice>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== mzemanek/Operations-Research/Samples/Sample.Minimize.out.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="Default.xsl"?>
<OperationsResearch xsi:schemaLocation="http://www.fom.de/schemas/operations-research/ws-11 Simplex-v1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Simplex mode="Minimize">
    <Tableaux>
      <Tableau index="0">
        <Columns>
          <Column n="1">x1</Column>
          <Column n="2">x2</Column>
          <Column n="3">s1</Column>
          <Column n="4">e2</Column>
          <Column n="5">k(0)</Column>
          <Column n="6"></Column>
        </Columns>
        <Pivot m="3" n="1" />
        <Rows>
          <Row m="1" function="I" transform="Z1 - 1/4 * Z3">
            <Column n="1">1/4</Column>
            <Column n="2">0</Column>
            <Column n="3">1</Column>
            <Column n="4">0</Column>
            <Column n="5">0</Column>
            <Column n="6">1 1/2</Column>
            <Ratio>6</Ratio>
          </Row>
          <Row m="2" function="II" transform="Z2 - 1 * Z3">
            <Column n="1">1</Column>
            <Column n="2">1</Column>
            <Column n="3">0</Column>
            <Column n="4">0</Column>
            <Column n="5">0</Column>
            <Column n="6">10</Column>
            <Ratio>10</Ratio>
          </Row>
          <Row m="3" function="III" transform="AZ / 2">
            <Column n="1">2</Column>
            <Column n="2">0</Column>
            <Column n="3">0</Column>
            <Column n="4">1</Column>
            <Column n="5">0</Column>
            <Column n="6">10</Column>
            <Ratio>5</Ratio>
          </Row>
          <Row m="4" function="k" transform="Z4 - 1 * Z3">
            <Column n="1">1</Column>
            <Column n="2">0</Column>
            <Column n="3">0</Column>
            <Column n="4">0</Column>
            <Column n="5">1</Column>
            <Column n="6">30</Column>
            <Ratio>undefined</Ratio>
          </Row>
        </Rows>
        <Solution>
          <Column n="1">1</Column>
          <Column n="2">0</Column>
          <Column n="3">0</Column>
          <Column n="4">0</Column>
          <Column n="5">undefined</Column>
          <Column n="6">30</Column>
        </Solution>
      </Tableau>
      <Tableau index="1">
        <Columns>
          <Column n="1">x1</Column>
          <Column n="2">x2</Column>
          <Column n="3">s1</Column>
          <Column n="4">e2</Column>
          <Column n="5">k(0)</Column>
          <Column n="6"></Column>
        </Columns>
        <Pivot m="0" n="0" />
        <Rows>
          <Row m="1" function="I">
            <Column n="1">0</Column>
            <Column n="2">0</Column>
            <Column n="3">1</Column>
            <Column n="4">-1/8</Column>
            <Column n="5">0</Column>
            <Column n="6">1/4</Column>
            <Ratio />
          </Row>
          <Row m="2" function="II">
            <Column n="1">0</Column>
            <Column n="2">1</Column>
            <Column n="3">0</Column>
            <Column n="4">-1/2</Column>
            <Column n="5">0</Column>
            <Column n="6">5</Column>
            <Ratio />
          </Row>
          <Row m="3" function="III">
            <Column n="1">1</Column>
            <Column n="2">0</Column>
            <Column n="3">0</Column>
            <Column n="4">1/2</Column>
            <Column n="5">0</Column>
            <Column n="6">5</Column>
            <Ratio />
          </Row>
          <Row m="4" function="k">
            <Column n="1">0</Column>
            <Column n="2">0</Column>
            <Column n="3">0</Column>
            <Column n="4">-1/2</Column>
            <Column n="5">1</Column>
            <Column n="6">25</Column>
            <Ratio />
          </Row>
        </Rows>
        <Solution>
          <Column n="1">5</Column>
          <Column n="2">5</Column>
          <Column n="3">1/4</Column>
          <Column n="4">0</Column>
          <Column n="5">undefined</Column>
          <Column n="6">25</Column>
        </Solution>
      </Tableau>
    </Tableaux>
  </Simplex>
</OperationsResearch>

=== mzemanek/Operations-Research/Samples/Sample.Maximize.out.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="Default.xsl"?>
<OperationsResearch xsi:schemaLocation="http://www.fom.de/schemas/operations-research/ws-11 Simplex-v1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Simplex mode="Maximize">
    <Tableaux>
      <Tableau index="0">
        <Columns>
          <Column n="1">x1</Column>
          <Column n="2">x2</Column>
          <Column n="3">s1</Column>
          <Column n="4">s2</Column>
          <Column n="5">s3</Column>
          <Column n="6">s4</Column>
          <Column n="7">g(0)</Column>
          <Column n="8"></Column>
        </Columns>
        <Pivot m="1" n="1" />
        <Rows>
          <Row m="1" function="I" transform="AZ / 1">
            <Column n="1">1</Column>
            <Column n="2">0</Column>
            <Column n="3">1</Column>
            <Column n="4">0</Column>
            <Column n="5">0</Column>
            <Column n="6">0</Column>
            <Column n="7">0</Column>
            <Column n="8">12</Column>
            <Ratio>12</Ratio>
          </Row>
          <Row m="2" function="II" transform="Z2 - 0 * Z1">
            <Column n="1">0</Column>
            <Column n="2">1</Column>
            <Column n="3">0</Column>
            <Column n="4">1</Column>
            <Column n="5">0</Column>
            <Column n="6">0</Column>
            <Column n="7">0</Column>
            <Column n="8">15</Column>
            <Ratio>0</Ratio>
          </Row>
          <Row m="3" function="III" transform="Z3 - 1 * Z1">
            <Column n="1">1</Column>
            <Column n="2">3</Column>
            <Column n="3">0</Column>
            <Column n="4">0</Column>
            <Column n="5">1</Column>
            <Column n="6">0</Column>
            <Column n="7">0</Column>
            <Column n="8">51</Column>
            <Ratio>51</Ratio>
          </Row>
          <Row m="4" function="g" transform="Z4 - 3 * Z1">
            <Column n="1">3</Column>
            <Column n="2">1</Column>
            <Column n="3">0</Column>
            <Column n="4">0</Column>
            <Column n="5">0</Column>
            <Column n="6">1</Column>
            <Column n="7">0</Column>
            <Column n="8">41</Column>
            <Ratio>13 2/3</Ratio>
          </Row>
          <Row m="5" function="" transform="Z5 - -9 * Z1">
            <Column n="1">-9</Column>
            <Column n="2">-3</Column>
            <Column n="3">0</Column>
            <Column n="4">0</Column>
            <Column n="5">0</Column>
            <Column n="6">0</Column>
            <Column n="7">1</Column>
            <Column n="8">0</Column>
            <Ratio>undefined</Ratio>
          </Row>
        </Rows>
        <Solution>
          <Column n="1">-9</Column>
          <Column n="2">-3</Column>
          <Column n="3">0</Column>
          <Column n="4">0</Column>
          <Column n="5">0</Column>
          <Column n="6">0</Column>
          <Column n="7">undefined</Column>
          <Column n="8">0</Column>
        </Solution>
      </Tableau>
      <Tableau index="1">
        <Columns>
          <Column n="1">x1</Column>
          <Column n="2">x2</Column>
          <Column n="3">s1</Column>
          <Column n="4">s2</Column>
          <Column n="5">s3</Column>
          <Column n="6">s4</Column>
          <Column n="7">g(0)</Column>
          <Column n="8"></Column>
        </Columns>
        <Pivot m="4" n="2" />
        <Rows>
          <Row m="1" function="I" transform="Z1 - 0 * Z4">
            <Column n="1">1</Column>
            <Column n="2">0</Column>
            <Column n="3">1</Column>
            <Column n="4">0</Column>
            <Column n="5">0</Column>
            <Column n="6">0</Column>
            <Column n="7">0</Column>
            <Column n="8">12</Column>
            <Ratio>0</Ratio>
          </Row>
          <Row m="2" function="II" transform="Z2 - 1 * Z4">
            <Column n="1">0</Column>
            <Column n="2">1</Column>
            <Column n="3">0</Column>
            <Column n="4">1</Column>
            <Column n="5">0</Column>
            <Column n="6">0</Column>
            <Column n="7">0</Column>
            <Column n="8">15</Column>
            <Ratio>15</Ratio>
          </Row>
          <Row m="3" function="III" transform="Z3 - 3 * Z4">
            <Column n="1">0</Column>
            <Column n="2">3</Column>
            <Column n="3">-1</Column>
            <Column n="4">0</Column>
            <Column n="5">1</Column>
            <Column n="6">0</Column>
            <Column n="7">0</Column>
            <Column n="8">39</Column>
            <Ratio>13</Ratio>
          </Row>
          <Row m="4" function="g" transform="AZ / 1">
            <Column n="1">0</Column>
            <Column n="2">1</Column>
            <Column n="3">-3</Column>
            <Column n="4">0</Column>
            <Column n="5">0</Column>
            <Column n="6">1</Column>
            <Column n="7">0</Column>
            <Column n="8">5</Column>
            <Ratio>5</Ratio>
          </Row>
          <Row m="5" function="" transform="Z5 - -3 * Z4">
            <Column n="1">0</Column>
            <Column n="2">-3</Column>
            <Column n="3">9</Column>
            <Column n="4">0</Column>
            <Column n="5">0</Column>
            <Column n="6">0</Column>
            <Column n="7">1</Column>
            <Column n="8">108</Column>
            <Ratio>undefined</Ratio>
          </Row>
        </Rows>
        <Solution>
          <Column n="1">12</Column>
          <Column n="2">0</Column>
          <Column n="3">0</Column>
          <Column n="4">15</Column>
          <Column n="5">39</Column>
          <Column n="6">5</Column>
          <Column n="7">undefined</Column>
          <Column n="8">108</Column>
        </Solution>
      </Tableau>
      <Tableau index="2">
        <Columns>
          <Column n="1">x1</Column>
          <Column n="2">x2</Column>
          <Column n="3">s1</Column>
          <Column n="4">s2</Column>
          <Column n="5">s3</Column>
          <Column n="6">s4</Column>
          <Column n="7">g(0)</Column>
          <Column n="8"></Column>
        </Columns>
        <Pivot m="0" n="0" />
        <Rows>
          <Row m="1" function="I">
            <Column n="1">1</Column>
            <Column n="2">0</Column>
            <Column n="3">1</Column>
            <Column n="4">0</Column>
            <Column n="5">0</Column>
            <Column n="6">0</Column>
            <Column n="7">0</Column>
            <Column n="8">12</Column>
            <Ratio />
          </Row>
          <Row m="2" function="II">
            <Column n="1">0</Column>
            <Column n="2">0</Column>
            <Column n="3">3</Column>
            <Column n="4">1</Column>
            <Column n="5">0</Column>
            <Column n="6">-1</Column>
            <Column n="7">0</Column>
            <Column n="8">10</Column>
            <Ratio />
          </Row>
          <Row m="3" function="III">
            <Column n="1">0</Column>
            <Column n="2">0</Column>
            <Column n="3">8</Column>
            <Column n="4">0</Column>
            <Column n="5">1</Column>
            <Column n="6">-3</Column>
            <Column n="7">0</Column>
            <Column n="8">24</Column>
            <Ratio />
          </Row>
          <Row m="4" function="g">
            <Column n="1">0</Column>
            <Column n="2">1</Column>
            <Column n="3">-3</Column>
            <Column n="4">0</Column>
            <Column n="5">0</Column>
            <Column n="6">1</Column>
            <Column n="7">0</Column>
            <Column n="8">5</Column>
            <Ratio />
          </Row>
          <Row m="5" function="">
            <Column n="1">0</Column>
            <Column n="2">0</Column>
            <Column n="3">0</Column>
            <Column n="4">0</Column>
            <Column n="5">0</Column>
            <Column n="6">3</Column>
            <Column n="7">1</Column>
            <Column n="8">123</Column>
            <Ratio />
          </Row>
        </Rows>
        <Solution>
          <Column n="1">12</Column>
          <Column n="2">5</Column>
          <Column n="3">0</Column>
          <Column n="4">10</Column>
          <Column n="5">24</Column>
          <Column n="6">0</Column>
          <Column n="7">undefined</Column>
          <Column n="8">123</Column>
        </Solution>
      </Tableau>
    </Tableaux>
  </Simplex>
</OperationsResearch>

=== mzemanek/Operations-Research/Samples/Sample.xml
<?xml version="1.0" encoding="utf-8" ?>
<OperationsResearch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.fom.de/schemas/operations-research/ws-11 Simplex-v1.0.xsd">
   <!-- x1, x2, s1, s2, s3, s4, g(0), <Empty> -->
   <!-- I, II, III, IV, Zielfunktion -->
   <Simplex>
      <Tableaux>
         <Tableau index="0">
            <Columns>
               <Column index="0">x1</Column>
               <Column index="1">x1</Column>
               <Column index="2">x1</Column>
               <Column index="3">x1</Column>
               <Column index="4">x1</Column>
               <Column index="5">x1</Column>
               <Column index="6">x1</Column>
               <Column index="7">x1</Column>
            </Columns>
            <Elements>
               <Element m="0" n="0">1</Element>
               <Element m="0" n="1">0</Element>
               <Element m="0" n="2">1</Element>
               <Element m="0" n="3">0</Element>
               <Element m="0" n="4">0</Element>
               <Element m="0" n="5">0</Element>
               <Element m="0" n="6">0</Element>
               <Element m="0" n="7">12</Element>

               <Element m="1" n="0">0</Element>
               <Element m="1" n="1">1</Element>
               <Element m="1" n="2">0</Element>
               <Element m="1" n="3">1</Element>
               <Element m="1" n="4">0</Element>
               <Element m="1" n="5">0</Element>
               <Element m="1" n="6">0</Element>
               <Element m="1" n="7">15</Element>

               <Element m="2" n="0">1</Element>
               <Element m="2" n="1">3</Element>
               <Element m="2" n="2">0</Element>
               <Element m="2" n="3">0</Element>
               <Element m="2" n="4">1</Element>
               <Element m="2" n="5">0</Element>
               <Element m="2" n="6">0</Element>
               <Element m="2" n="7">51</Element>

               <Element m="3" n="0">3</Element>
               <Element m="3" n="1">1</Element>
               <Element m="3" n="2">0</Element>
               <Element m="3" n="3">0</Element>
               <Element m="3" n="4">0</Element>
               <Element m="3" n="5">1</Element>
               <Element m="3" n="6">0</Element>
               <Element m="3" n="7">41</Element>

               <Element m="4" n="0">-9</Element>
               <Element m="4" n="1">-3</Element>
               <Element m="4" n="2">0</Element>
               <Element m="4" n="3">0</Element>
               <Element m="4" n="4">0</Element>
               <Element m="4" n="5">0</Element>
               <Element m="4" n="6">1</Element>
               <Element m="4" n="7">0</Element>
            </Elements>
            <Solution>
               <Element n="0">0</Element>
               <Element n="1">0</Element>
               <Element n="2">12</Element>
               <Element n="3">15</Element>
               <Element n="4">51</Element>
               <Element n="5">41</Element>
               <Element n="7">0</Element>
            </Solution>
         </Tableau>
      </Tableaux>
      <Transformations>
         <Transformation tableau="0">
            <Solution>
               <Element n="0">0</Element>
               <Element n="1">0</Element>
               <Element n="2">12</Element>
               <Element n="3">15</Element>
               <Element n="4">51</Element>
               <Element n="5">41</Element>
               <Element n="7">0</Element>
            </Solution>
         </Transformation>
      </Transformations>
   </Simplex>

   <Tableau index="">
      <RowTransformations>
         <RowTransformation index="0"></RowTransformation>
      </RowTransformations>
      <Rows>
         <Row index="">

         </Row>
      </Rows>
   </Tableau>
</OperationsResearch>
